### ISSUE TITLE
Ensure the matrix service can handle the expected number of concurrent requests from users

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/matrix-service#184]
During our March 19 meeting, Parth noted that this issue requires a script to scale up our datasets at will.

- [x] MUST complete 30 requests for 50,000 cell matrices 
- [x] SHOULD complete within 10 minutes
- [x] MUST complete requests for the entire _HCA_ [but might take awhile]

From [Availability and SLOs with scale testing](https://docs.google.com/document/d/1OrKjfDR97fTugXprgkundI8i4k8SNOizcoz5fRTb8PU/edit#), Ambrose also commented:

_I imagine that our most common request will be "give me all the cells for <tissue>" followed by "give me all the cells". I have not validated this suspicion with users._

_If the per-tissue requests are smaller than 50,000, then this will work. I worry a bit that we'll need to field larger requests for immune cells._

SLOs requirements document: https://docs.google.com/document/d/1OrKjfDR97fTugXprgkundI8i4k8SNOizcoz5fRTb8PU/edit#

**Comment by brianraymor** [comment]
The _ SHOULD complete within 10 minutes_ will not be addressed until Q3 2019.
